### ISSUE TITLE
Real-CUGAN License

### ISSUE THREAD

**Issue by Kim2091** [muslll/neosr#18]
It appears to be listed here? https://github.com/bilibili/ailab/blob/main/Real-CUGAN/LICENSE

You have it marked as "Unknown" in your LICENSE file. 

I'm also somewhat concerned about having code merged in that has no known license, like [DCTLSA](https://github.com/zengkun301/DCTLSA). Wouldn't it be preferable to wait until you know what the license is?

**Comment by muslll** [comment]
Thanks, I have added the Real-CUGAN license.
About code with unknown licenses, they are open source and the likelyhood of it not being under a permissive open source license is minimal. With that being said, no authors have expressed concerns about it as of speaking, otherwise we would have agreed to keep or remove it.

**Comment by Kim2091** [comment]
@muslll It's easier to tack onto this issue. DCTLSA posted their license on the repo: https://github.com/zengkun301/DCTLSA#license
