### ISSUE TITLE
Support safetensors as pretrained models

### ISSUE THREAD

**Issue by RunDevelopment** [muslll/neosr#36]
We plan to support and push safetensors on OMDB in the future for security reasons. So it would be great if neosr could support them.

**Comment by muslll** [comment]
Looking back a this, safetensors support would offer no benefit now. Pytorch is switching torch.load to `weights_only` by default, which prevents arbitrary code execution, and neosr already loads all models with `weights_only` for a long time now. Safetensors main 'selling point' was the safety of the format, so I don't think there's any point in using it anymore, at least for our purpose, since we work with small models and don't do any major processing that would benefit from lazy loading. Adding it to neosr would just be yet another dependency, for no real reason, in my opinion. People can still convert pickle to safetensor if they want to, using chaiNNer for example.
If anybody wants to point a particular reason to support it that I'm perhaps not seeing, feel free to do so and we can revisit it in the future. Otherwise I'm closing it for now.
