### ISSUE TITLE
and again rgb_mean

### ISSUE THREAD

**Issue by umzi2** [muslll/neosr#67]
hello, I noticed a long time ago that in commit: 417432c, you changed rgb_mean(0.5,0.5,0.5) but I didn’t ask because I knew, but now I noticed that because of this, when using the official code, a color shift occurs, I think it’s worth return official values ​​or add flags to models with architectures with rgb_mean
https://slow.pics/s/2GVfqi66

**Comment by muslll** [comment]
You can force the old values using the [arch-specific options](https://github.com/muslll/neosr/wiki/Arch%E2%80%90specific-options). I don't intend to reverse this change, because it's the easiest way to improve stability on datasets with mean/std values that are very different than that of ImageNet1k.
