### ISSUE TITLE
Suggestions/corrections for setup/walkthrough page

### ISSUE THREAD

**Issue by pokepress** [muslll/neosr#85]
> The -opt argument specifies the configuration file. It must be in YAML format.
> 
> python train.py -opt config.toml

Out of date and inconsistent.

> The use_hflip and use_rot options are augmentations. It will rotate and flip images during training to increase variety. This is a standard basic augmentation that has been shown to improve models. Defaults to true even if not present in the configuration file.

So, I've actually been working primarily with upscaling video, and I don't think this is a good combination. Digital film scans might be okay, but analog video actually seems to train more poorly with these optimizations, particularly rotation. Analog video tends to have per-line patterns (color offset from luma, etc.), and as such flipping or rotating the image can confuse the training process rather than properly diversifying the dataset. This should at least be mentioned.

**Comment by muslll** [comment]
Hi.
> Out of date and inconsistent.

Fixed.

> I don't think this is a good combination

It's a common augmentation. It may not benefit for your usage, but in most cases it helps to prevent overfitting. Users can always disable it manually if they wish, of course.

**Comment by pokepress** [comment]
> It's a common augmentation. It may not benefit for your usage, but in most cases it helps to prevent overfitting. Users can always disable it manually if they wish, of course.

I get what you're saying, and I agree in a lot of cases it makes sense. I just think it's common enough that maybe there should be a brief note. I think I also got tripped up because the old templates had it specified explicitly, and the new ones don't. Sorry if I came across a little terse there.

**Comment by muslll** [comment]
No problem.
> there should be a brief note

Well, it's described on the wiki. The only cases where flip/rotation would badly impact the results would be if your degradation has a fixed pattern 'noise' that you want to remain in the same direction. It's a pretty specific need, to be honest. And even in those cases, we have had people in the community training on degradations like that (bad deinterlaced footage for example) and flip/rotation didn't cause any issue there.

> the old templates had it specified explicitly, and the new ones don't

Yeah, I removed some options on the templates because there's too many. So the goal was to make it clean and simple, and then if the user needs to change some specific option not in the templates it would be listed on the wiki.
Thanks for your feedback by the way. Let me know if you find anything else that could be improved :+1:
